name: ofc

on: 
  release:
    types: [published]
  push:
    branches:
      - master
    tags:
    - 'v*'
  schedule:
    - cron: 
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install requests
      run: |
        pip install requests
        pip install pynacl
    - name: read config from secrets
      env: 
        id: ${{ secrets.CONFIG_ID }}
        secret: ${{ secrets.CONFIG_KEY }}        
        refresh_token: ${{secrets.REFRESH_TOKEN}}
      run: |    
        python ofc.py
    - name: commit
      run: |
        git config --global user.email  "fuongtd@gmail.com"
        git config --global user.name "fuongtd"
        git add .
        git commit -m "update new token" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
